services:
  api:
    # 1. Production Command: Run Gunicorn (copied from your old entrypoint.sh)
    command: gunicorn ChronosAtlas.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --error-logfile - --log-level info
    
    # 2. Production Settings Module
    environment:
      - DJANGO_SETTINGS_MODULE=ChronosAtlas.settings.prod
      
    # 3. Production Volumes (Only mount data/static directories, not source code)
    # Assumes you want to persist collected static files or user data.
    volumes:
      - ./staticfiles:/app/staticfiles 
      # Add other production-related volumes here (e.g., user-uploaded media)
      
    # 4. Use a secure production .env file
    env_file:
      - .env.prod
    
    # Optional: Increase resource limits for production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
