version: '3.8'

# This file contains the shared configuration (Build, DB setup, Networks)
# It now defines the PRODUCTION command as the default, which will be overridden 
# by docker-compose.dev.yml when running development.

services:
  api:
    build: .
    restart: always
    depends_on:
      - db
      
    # CRITICAL FIX: Define the production command as the default.
    # This prevents the 'exec "$@"' in entrypoint.sh from being empty.
    command: gunicorn ChronosAtlas.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 120 --error-logfile - --log-level info

    # CRITICAL FIX: Define the production settings as the default.
    environment:
      - DJANGO_SETTINGS_MODULE=ChronosAtlas.settings.prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=chronosuser
      - DB_NAME=chronosatlas
      
    # Dev mode will add 'ports' and override 'command' and 'DJANGO_SETTINGS_MODULE'

    # Use a base .env file for secrets that might be shared (like a base SECRET_KEY)
    env_file:
      - .env
      
  db:
    image: postgres:14.19-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # These credentials MUST match the defaults used in the entrypoint.sh script
      - POSTGRES_DB=chronosatlas
      - POSTGRES_USER=chronosuser
      - POSTGRES_PASSWORD=chronospassword
      
volumes:
  postgres_data:
