services:
  db:
    image: postgres:14-alpine
    container_name: chronos_db
    # This explicitly sets the credentials for the database service.
    environment:
      POSTGRES_USER: chronosuser
      POSTGRES_PASSWORD: chronospassword # <--- MUST MATCH DATABASE_URL
      POSTGRES_DB: chronosatlas
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: chronos_api
    # REMOVED: The conflicting 'command' line. 
    # Docker will now correctly use the ENTRYPOINT from the Dockerfile 
    # (/usr/local/bin/entrypoint.sh).
    volumes:
      - .:/usr/src/app
    # CHANGED: Mapping internal 8000 to external 8080 to avoid conflicts
    ports:
      - "8080:8000" 
    # This is the file we just created
    env_file:
      - .env.prod
    # This is the variable used by Django/psycopg2 to connect.
    # It must match the credentials defined in the 'db' service above.
    environment:
      DATABASE_URL: postgres://chronosuser:chronospassword@db:5432/chronosatlas
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
