# Generated by Django 5.2.6 on 2025-09-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('birth_year', models.IntegerField(help_text='Year of birth (use negative for BCE)')),
                ('death_year', models.IntegerField(blank=True, help_text='Year of death (null if still alive)', null=True)),
                ('fields', models.ManyToManyField(to='timeline.field')),
            ],
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influenced_by_set', to='timeline.figure')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences_set', to='timeline.figure')),
            ],
            options={
                'unique_together': {('influencer', 'influenced')},
            },
        ),
    ]
