# Generated by Django 5.0 on 2025-09-28 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0006_figure_fields'),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influenced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences_received', to='figures.figure')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences_given', to='figures.figure')),
            ],
            options={
                'verbose_name': 'Influence Relationship',
                'verbose_name_plural': 'Influence Relationships',
                'unique_together': {('influencer', 'influenced')},
            },
        ),
    ]
