# Generated by Django 5.0 on 2025-09-30 14:15

from django.contrib.postgres.indexes import GistIndex
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        # This operation enables the 'btree_gist' extension in PostgreSQL.
        # While it might have been enabled by the figures migration,
        # including it here makes this migration self-contained and robust.
        BtreeGistExtension(),
        # This index optimizes queries that filter for timeline events
        # occurring in a specific year or range of years.
        migrations.AddIndex(
            model_name="timelineevent",
            index=GistIndex(
                fields=["year"],
                name="timeline_event_year_gist_idx",
            ),
        ),
    ]
