# Generated by Django 5.0 on 2025-10-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_add_timeline_gist_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timelineevent',
            name='timeline_event_year_gist_idx',
        ),
    ]
