# Generated by Django 5.0 on 2025-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthYear', models.IntegerField(db_column='birth_year', default=0)),
                ('deathYear', models.IntegerField(blank=True, db_column='death_year', null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['birthYear'],
            },
        ),
    ]
