# Generated by Django 5.0 on 2025-10-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_add_timeseries_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='figure',
            name='figure_lifespan_gist_idx',
        ),
        migrations.AlterField(
            model_name='figure',
            name='summary',
            field=models.TextField(default='', help_text='A brief summary or description of the figure.'),
        ),
    ]
