# Generated by Django 5.0 on 2025-09-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_add_core_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='wikidata_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
