# Generated by Django 5.0 on 2025-10-02 12:24

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_remove_figure_figure_lifespan_gist_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name'], 'verbose_name': 'Field of Endeavor', 'verbose_name_plural': 'Fields of Endeavor'},
        ),
        migrations.AlterModelOptions(
            name='figure',
            options={'ordering': ['normalized_birth_year', 'name'], 'verbose_name': 'Figure', 'verbose_name_plural': 'Figures'},
        ),
        migrations.RemoveField(
            model_name='figure',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='instance_of_QIDs',
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(default='placeholder-slug', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='figure',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figures', to='figures.field'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='normalized_birth_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='normalized_death_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='figure',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=django.contrib.postgres.indexes.GistIndex(models.Func(models.F('normalized_birth_year'), models.F('normalized_death_year'), function='int4range', output_field=django.contrib.postgres.fields.ranges.RangeField), name='figure_lifespan_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['name'], name='figures_fig_name_d07800_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['slug'], name='figures_fig_slug_46943b_idx'),
        ),
        migrations.AddConstraint(
            model_name='figure',
            constraint=models.CheckConstraint(check=models.Q(('normalized_birth_year__lte', models.F('normalized_death_year'))), name='birth_before_death'),
        ),
        migrations.AddConstraint(
            model_name='figure',
            constraint=models.UniqueConstraint(fields=('normalized_birth_year', 'normalized_death_year'), name='unique_lifespan'),
        ),
        migrations.AlterModelTable(
            name='figure',
            table='figures_figure',
        ),
    ]
