# Generated by Django 5.0 on 2025-10-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0004_delete_occupation_alter_field_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='figure',
            options={'verbose_name': 'Figure', 'verbose_name_plural': 'Figures'},
        ),
        migrations.AddField(
            model_name='figure',
            name='fields',
            field=models.ManyToManyField(related_name='figures_set', to='figures.field'),
        ),
    ]
