# Generated by Django 5.0 on 2025-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0005_add_gist_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='fields',
            field=models.ManyToManyField(related_name='figures', to='figures.field'),
        ),
    ]
