name: CI

on:
  push:
    branches: [ dev-stage, main ]
  pull_request:
    branches: [ dev-stage, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: chronosuser
          POSTGRES_PASSWORD: chronospassword
          POSTGRES_DB: chronosatlas
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U chronosuser -d chronosatlas" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DJANGO_SETTINGS_MODULE: ChronosAtlas.settings_dev
      DATABASE_URL: postgres://chronosuser:chronospassword@localhost:5432/chronosatlas
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test
